---
- hosts: cloudatcost
  tasks:
    - name: Update apt-cache
      apt: update_cache=yes
    - name: Add user (<NAME>) - with preferred shell - zsh
      user: name=<NAME> comment="" groups=sudo shell=/bin/zsh
