---
- hosts: cloudatcost
  tasks:
    - name: Update apt-cache
      apt: update_cache=yes
    - name: install zsh
      apt: name=zsh state=present
    - name: Add user (caesarabby)
      user: name=caesarabby comment="Caesar Abby" groups=sudo shell=/bin/zsh
